image: registry.gitlab.com/gitlab-org/terraform-images/stable:latest

variables:
  AWS_PROFILE: ${CI_COMMIT_BRANCH}
  TF_STATE: "tf_state"
  TF_ADDRESS: ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/terraform/state/${TF_STATE}

cache:
  key: ${TF_STATE}
  paths:
    - .terraform

stages:
  - validate
  - build
  - deploy
  - destroy


init:
  stage: .pre
  script:
    - terraform init

fmt:
  stage: .pre
  script:
    - terraform fmt

validate:
  stage: validate
  script:
    - terraform validate

plan:
  stage: build
  script:
    - terraform plan
    - terraform plan-json
  artifacts:
    name: plan
    paths:
      - plan.cache
    reports:
      terraform: plan.json

apply:
  stage: deploy
  script:
    - terraform apply
  dependencies:
    - plan
  when: manual
  only:
    - main

destroy:
  stage: destroy
  script:
    - terraform destroy
  dependencies:
    - apply
  when: manual
  only:
    - main